esphome:
  name: esp8266amica

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "your_key"

ota:
  password: "your_password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266Amica Fallback Hotspot"
    password: "your_password"

captive_portal:
sensor:
    platform: dht
    model: DHT11
    pin: D8
    temperature:
      name: "Temperatura"
      id: "temp"
    humidity:
      name: "Humidade"
      id: "hum"
    update_interval: 10s

i2c:
  sda: D2
  scl: D1

display:
  - platform: lcd_pcf8574
    dimensions: 16x2
    address: 0x27
    lambda: |-
      it.printf("%.1f~", id(temp).state);
